/**
 * GENERATED by scripts/abstract-media.ts – do not edit by hand.
 * Answer keys for the abstract-reasoning questions: Director side only, like ./scoring.ts.
 */
import type { ExerciseMeta } from '../../../src/insight/index.js';

export const ABSTRACT_SCORING: Record<string, ExerciseMeta> = {
  'ar-01': { family: 'abstract-matrix', dimension: 'think', modality: 'visual', risk: 'low', correctAnswer: 'c' },
  'ar-02': { family: 'abstract-matrix', dimension: 'think', modality: 'visual', risk: 'low', correctAnswer: 'f' },
  'ar-03': { family: 'abstract-matrix', dimension: 'think', modality: 'visual', risk: 'low', correctAnswer: 'a' },
  'ar-04': { family: 'abstract-matrix', dimension: 'think', modality: 'visual', risk: 'low', correctAnswer: 'd' },
  'ar-05': { family: 'abstract-matrix', dimension: 'think', modality: 'visual', risk: 'low', correctAnswer: 'g' },
  'ar-06': { family: 'abstract-matrix', dimension: 'think', modality: 'visual', risk: 'low', correctAnswer: 'b' },
  'ar-07': { family: 'abstract-matrix', dimension: 'think', modality: 'visual', risk: 'low', correctAnswer: 'e' },
  'ar-08': { family: 'abstract-matrix', dimension: 'think', modality: 'visual', risk: 'low', correctAnswer: 'h' },
};
