/**
 * GENERATED by scripts/abstract-media.ts – do not edit by hand.
 * Answer keys for the abstract-reasoning questions: Director side only, like ./scoring.ts.
 */
import type { ExerciseMeta } from '../../../src/insight/index.js';

export const ABSTRACT_SCORING: Record<string, ExerciseMeta> = {
  'ar-03': { family: 'abstract-matrix', dimension: 'think', modality: 'visual', risk: 'low', correctAnswer: 'a' },
  'ar-04': { family: 'abstract-matrix', dimension: 'think', modality: 'visual', risk: 'low', correctAnswer: 'd' },
  'ar-05': { family: 'abstract-matrix', dimension: 'think', modality: 'visual', risk: 'low', correctAnswer: 'g' },
  'ar-06': { family: 'abstract-matrix', dimension: 'think', modality: 'visual', risk: 'low', correctAnswer: 'b' },
  'ar-07': { family: 'abstract-matrix', dimension: 'think', modality: 'visual', risk: 'low', correctAnswer: 'e' },
  'ar-08': { family: 'abstract-matrix', dimension: 'think', modality: 'visual', risk: 'low', correctAnswer: 'h' },
};

/** The rules behind each puzzle, for the Directors' question book. */
export const ABSTRACT_RULES: Record<string, string> = {
  'ar-03': "Count: third = first + second. Shape: same across a row. Fill: each once per row and column.",
  'ar-04': "Shape, count and size: each value once per row and column (three independent rules).",
  'ar-05': "Arrow: turns a quarter clockwise each step. Dot: moves one corner clockwise each step.",
  'ar-06': "Lines: the third tile keeps the lines that appear in only one of the first two; shared lines disappear.",
  'ar-07': "Count: third = first − second. Shape and fill: each once per row and column.",
  'ar-08': "Arrow: in row n it turns n × 45° clockwise each step. Fill: each once per row and column.",
};
