/**
 * DEMO assessment content – display only (no answer keys).
 * The scoring metadata lives in ./scoring.ts, which the employee app never imports.
 */
import type { AssessmentDefinition, MediaRef } from '../../../src/runner/index.js';
import { ABSTRACT_QUESTIONS } from './abstractItems.js';

const media = (file: string, sha256: string, alt: string): MediaRef => ({
  src: `./assessment-media/demo/${file}`,
  sha256,
  alt,
});

export const DEMO_ASSESSMENT: AssessmentDefinition = {
  version: 'focusiq-demo-2026.1',
  title: 'FocusiQ assessment (demo)',
  estimatedMinutes: 30,
  sections: [
    {
      id: 'reading',
      title: 'Reading and deciding',
      instructions: [
        'There is no time limit in this section – work in the way you normally would.',
        'You can move back and forth between questions in this section before you submit it.',
      ],
      rememberThis: [
        'Account WG-2041 is The Harbour Hotel. They receive a 12% trade discount.',
        'Standard welcome packs can be delivered any weekday. Bespoke welcome packs need 3–5 working days.',
        'Any quote over £5,000 needs Director sign-off.',
      ],
      shuffleQuestions: true,
      scored: true,
      questions: [
        {
          questionVersionId: 'demo-q01',
          kind: 'single_choice',
          stem: 'A hotel’s purchasing manager emails asking for a copy of last month’s invoice. What do you do?',
          options: [
            { id: 'a', text: 'Forward it to the accounts team so they send the correct invoice' },
            { id: 'b', text: 'Ask your manager before doing anything' },
            { id: 'c', text: 'Find the invoice in the system and send it yourself' },
            { id: 'd', text: 'Ask the purchasing manager why they need it' },
          ],
        },
        {
          questionVersionId: 'demo-q02',
          kind: 'single_choice',
          stem: 'Is this quote ready to send?',
          detail: [
            'Quote for The Harbour Hotel (WG-2041)',
            '50 × 300ml shampoo refill @ £4.20 = £210.00',
            'Trade discount applied: 10%',
            'Total after discount: £189.00',
          ],
          options: [
            { id: 'a', text: 'Yes, it is ready to send' },
            { id: 'b', text: 'No – the discount should be 12%' },
            { id: 'c', text: 'No – the line total is wrong' },
            { id: 'd', text: 'No – it needs Director sign-off' },
          ],
        },
        {
          questionVersionId: 'demo-q03',
          kind: 'single_choice',
          stem: 'On Monday, the head housekeeper at The Harbour Hotel orders bespoke welcome packs and asks for them on Wednesday. What do you tell them?',
          options: [
            { id: 'a', text: 'Bespoke packs need 3–5 working days, so Thursday at the earliest' },
            { id: 'b', text: 'Wednesday is fine – deliveries go out any weekday' },
            { id: 'c', text: 'Next week at the earliest' },
            { id: 'd', text: 'Wednesday, if you mark the order as urgent' },
          ],
        },
        {
          questionVersionId: 'demo-q04',
          kind: 'single_choice',
          stem: 'The system shows 40 boxes of barista sugar sticks, but the shelf count is 38. They sell about 200 boxes a month. What is the best next step?',
          options: [
            { id: 'a', text: 'Send the stock controller a direct email or Teams message with the details' },
            { id: 'b', text: 'Email the whole team so everyone is aware' },
            { id: 'c', text: 'Raise it with a Director' },
            { id: 'd', text: 'Correct the stock record yourself' },
          ],
        },
      ],
    },
    {
      id: 'quick',
      title: 'Quick decisions',
      instructions: [
        'This section is timed. A clock shows the time left for the whole section.',
        'If time runs out, the answers you have given so far are saved.',
        'Aim for a good answer rather than a perfect one.',
      ],
      timeLimitSeconds: 120,
      shuffleQuestions: true,
      scored: true,
      questions: [
        {
          questionVersionId: 'demo-q05',
          kind: 'single_choice',
          stem: 'Which tile comes next in the sequence?',
          image: media('sequence.svg', '076acec53c46cd20206f7d406421601887f6d7a57e404b19b2c4a8018864fcc0', 'A triangle pointing up, then right, then down, followed by a question mark.'),
          options: [
            { id: 'a', image: media('tri-up.svg', 'b489552cbd744e783935e9d2c0951345693f4d1423e805dece7c7654c2c08485', 'Triangle pointing up') },
            { id: 'b', image: media('tri-right.svg', '58efbdca44a76c0edece40519ddf2bcafccad0c93f5cf2ca2aae8445a8c5101b', 'Triangle pointing right') },
            { id: 'c', image: media('tri-down.svg', 'fcefcad42e0ef4f589616051ba81f79f198f90153a424a09a234acbef78dd749', 'Triangle pointing down') },
            { id: 'd', image: media('tri-left.svg', 'b20c3ed376184ee44924cd0aca0ee0485be18430626fce02d23670799a5960c3', 'Triangle pointing left') },
          ],
        },
        {
          questionVersionId: 'demo-q06',
          kind: 'single_choice',
          stem: 'Guest soaps come in cases of 25. A holiday park needs 160 soaps for its lodges. How many cases does it need?',
          options: [
            { id: 'a', text: '6' },
            { id: 'b', text: '7' },
            { id: 'c', text: '8' },
            { id: 'd', text: '6.4' },
          ],
        },
        {
          questionVersionId: 'demo-q07',
          kind: 'single_choice',
          stem: 'Rule: ship the order with the earliest promised date first. Which order ships first?',
          detail: ['Order 118 – Bayview Hotel, promised Thursday', 'Order 121 – Oakfield Lodges, promised Tuesday', 'Order 124 – The Grange Hotel, promised Wednesday', 'Order 125 – Seaview Holiday Park, promised Friday'],
          shuffleOptions: false,
          options: [
            { id: 'a', text: 'Order 118' },
            { id: 'b', text: 'Order 121' },
            { id: 'c', text: 'Order 124' },
            { id: 'd', text: 'Order 125' },
          ],
        },
        {
          questionVersionId: 'demo-q08',
          kind: 'single_choice',
          stem: 'A pack of bath mats sells for £20 and costs £15. A dispenser refill sells for £12 and costs £6. Which earns more profit for each one sold?',
          options: [
            { id: 'a', text: 'The pack of bath mats' },
            { id: 'b', text: 'The dispenser refill' },
            { id: 'c', text: 'They earn the same' },
          ],
        },
      ],
    },
    {
      id: 'abstract',
      title: 'Abstract reasoning',
      instructions: [
        'This section is timed: 4½ minutes for 6 puzzles. A clock shows the time left.',
        'Each grid follows rules across its rows and columns – for example shape, number, size, shading or direction. Several rules can apply at once.',
        'Choose the tile that completes the grid. If you are stuck, move on and come back: you can change answers until you submit the section.',
      ],
      timeLimitSeconds: 270,
      shuffleQuestions: false,
      scored: true,
      questions: ABSTRACT_QUESTIONS,
    },
    {
      id: 'code',
      title: 'Crack the code',
      instructions: [
        'This section is timed: 5 minutes for 4 codes. A clock shows the time left.',
        'Each lock has a secret code. No digit is used twice in a code.',
        'Each clue shows a guess and how close it was. Use all the clues together to work out the code.',
      ],
      timeLimitSeconds: 300,
      shuffleQuestions: false,
      scored: true,
      questions: [
        {
          questionVersionId: 'cc-01',
          kind: 'single_choice',
          stem: 'What is the 3-digit code?',
          detail: [
            '4 6 3  –  nothing is correct',
            '4 2 9  –  one digit is correct and in the right place',
            '9 7 3  –  two digits are correct but both in the wrong place',
            '6 8 1  –  one digit is correct and in the right place',
          ],
          shuffleOptions: false,
          options: [
            { id: 'a', text: '0 8 9' },
            { id: 'b', text: '5 2 1' },
            { id: 'c', text: '5 8 9' },
            { id: 'd', text: '6 3 9' },
            { id: 'e', text: '7 8 9' },
          ],
        },
        {
          questionVersionId: 'cc-02',
          kind: 'single_choice',
          stem: 'What is the 3-digit code?',
          detail: [
            '9 6 5  –  nothing is correct',
            '3 5 0  –  one digit is correct and in the right place',
            '4 7 2  –  one digit is correct and in the right place',
            '6 5 7  –  nothing is correct',
            '0 8 6  –  one digit is correct but in the wrong place',
          ],
          shuffleOptions: false,
          options: [
            { id: 'a', text: '4 0 1' },
            { id: 'b', text: '4 1 0' },
            { id: 'c', text: '4 3 0' },
            { id: 'd', text: '4 8 0' },
            { id: 'e', text: '4 9 0' },
          ],
        },
        {
          questionVersionId: 'cc-03',
          kind: 'single_choice',
          stem: 'What is the 3-digit code?',
          detail: [
            '5 6 4  –  nothing is correct',
            '0 5 8  –  one digit is correct but in the wrong place',
            '2 3 0  –  one digit is correct and in the right place',
            '9 6 2  –  one digit is correct and in the right place',
            '1 7 4  –  one digit is correct but in the wrong place',
          ],
          shuffleOptions: false,
          options: [
            { id: 'a', text: '4 6 0' },
            { id: 'b', text: '7 0 2' },
            { id: 'c', text: '9 1 0' },
            { id: 'd', text: '9 3 1' },
            { id: 'e', text: '9 7 0' },
          ],
        },
        {
          questionVersionId: 'cc-04',
          kind: 'single_choice',
          stem: 'What is the 4-digit code?',
          detail: [
            '7 1 3 4  –  one digit is correct and in the right place; one more is correct but in the wrong place',
            '2 3 0 1  –  one digit is correct and in the right place; one more is correct but in the wrong place',
            '2 7 3 0  –  one digit is correct and in the right place',
            '3 8 2 9  –  one digit is correct but in the wrong place',
            '5 1 3 7  –  one digit is correct and in the right place; two more are correct but in the wrong place',
          ],
          shuffleOptions: false,
          options: [
            { id: 'a', text: '1 6 3 5' },
            { id: 'b', text: '2 1 4 5' },
            { id: 'c', text: '2 1 7 5' },
            { id: 'd', text: '2 6 1 4' },
            { id: 'e', text: '6 5 3 1' },
          ],
        },
      ],
    },
    {
      id: 'numbers',
      title: 'Sales figures',
      instructions: [
        'This section is timed: 12 minutes for 10 questions. A clock shows the time left.',
        'Each question gives you some figures, like the ones a salesperson works with every day. Work out the answer as you would at work.',
        'You may use a calculator and paper.',
      ],
      timeLimitSeconds: 720,
      shuffleQuestions: false,
      scored: true,
      questions: [
        {
          questionVersionId: 'sm-01',
          kind: 'single_choice',
          stem: 'You are 14 working days into a 20-day month. How much do you need to sell on average each remaining working day to hit your target?',
          detail: ['Monthly target: £40,000', 'Sold so far: £26,500', 'Working days: 20 (14 gone)'],
          shuffleOptions: false,
          options: [
            { id: 'a', text: '£675' },
            { id: 'b', text: '£1,350' },
            { id: 'c', text: '£1,893' },
            { id: 'd', text: '£2,000' },
            { id: 'e', text: '£2,250' },
          ],
        },
        {
          questionVersionId: 'sm-02',
          kind: 'single_choice',
          stem: 'How many quotes do you need to send this year to reach your new-business target?',
          detail: ['New-business target: £120,000 a year', 'Average order: £1,500', 'Quotes that become orders: 25%'],
          shuffleOptions: false,
          options: [
            { id: 'a', text: '20' },
            { id: 'b', text: '80' },
            { id: 'c', text: '160' },
            { id: 'd', text: '320' },
            { id: 'e', text: '480' },
          ],
        },
        {
          questionVersionId: 'sm-03',
          kind: 'single_choice',
          stem: 'Last quarter, what percentage of your meetings turned into orders?',
          detail: ['Calls made: 200', 'Meetings booked: 50', 'Quotes sent: 20', 'Orders won: 8'],
          shuffleOptions: false,
          options: [
            { id: 'a', text: '4%' },
            { id: 'b', text: '10%' },
            { id: 'c', text: '16%' },
            { id: 'd', text: '25%' },
            { id: 'e', text: '40%' },
          ],
        },
        {
          questionVersionId: 'sm-04',
          kind: 'single_choice',
          stem: 'What is the gross margin on a welcome pack?',
          detail: ['Cost to Walter Geering: £2.40 a pack', 'Price to the hotel: £4.00 a pack'],
          shuffleOptions: false,
          options: [
            { id: 'a', text: '£1.60' },
            { id: 'b', text: '30%' },
            { id: 'c', text: '40%' },
            { id: 'd', text: '60%' },
            { id: 'e', text: '66.7%' },
          ],
        },
        {
          questionVersionId: 'sm-05',
          kind: 'single_choice',
          stem: 'A hotel group asks for 10% off. How many MORE units would you need to sell at the discounted price to make the same total profit as selling 1,000 at full price?',
          detail: ['Price: £10.00 a unit', 'Cost: £7.00 a unit', 'Discount asked for: 10% off the price'],
          shuffleOptions: false,
          options: [
            { id: 'a', text: '100' },
            { id: 'b', text: '333' },
            { id: 'c', text: '500' },
            { id: 'd', text: '1,100' },
            { id: 'e', text: '1,500' },
          ],
        },
        {
          questionVersionId: 'sm-06',
          kind: 'single_choice',
          stem: 'What is your weighted pipeline value: each opportunity’s value multiplied by its chance of winning, added together?',
          detail: ['Hotel A: £8,000 – 50% chance', 'Holiday park B: £20,000 – 10% chance', 'Hotel group C: £5,000 – 80% chance'],
          shuffleOptions: false,
          options: [
            { id: 'a', text: '£4,000' },
            { id: 'b', text: '£10,000' },
            { id: 'c', text: '£11,000' },
            { id: 'd', text: '£16,500' },
            { id: 'e', text: '£33,000' },
          ],
        },
        {
          questionVersionId: 'sm-07',
          kind: 'single_choice',
          stem: 'A hotel group’s target this year is 15% growth on last year. If it keeps spending at the same monthly rate, how will it finish against the target?',
          detail: ['Spend last year: £18,000', 'Target this year: last year + 15%', 'Spend so far: £13,200 after 9 months'],
          shuffleOptions: false,
          options: [
            { id: 'a', text: '£7,500 short' },
            { id: 'b', text: '£3,100 short' },
            { id: 'c', text: '£400 short' },
            { id: 'd', text: 'Exactly on target' },
            { id: 'e', text: '£2,700 over' },
          ],
        },
        {
          questionVersionId: 'sm-08',
          kind: 'single_choice',
          stem: 'You have time for one more call today. Which call has the higher expected profit (chance × order value × margin), and by how much?',
          detail: ['Call A: 60% chance of a £2,000 order at 35% margin', 'Call B: 30% chance of a £5,000 order at 20% margin'],
          shuffleOptions: false,
          options: [
            { id: 'a', text: 'Call A, by £120' },
            { id: 'b', text: 'Call A, by £280' },
            { id: 'c', text: 'They are the same' },
            { id: 'd', text: 'Call B, by £300' },
            { id: 'e', text: 'Call B, by £3,000' },
          ],
        },
        {
          questionVersionId: 'sm-09',
          kind: 'single_choice',
          stem: 'A holiday park reorders welcome packs every 6 weeks. If that continues, roughly what is the account worth over a year (52 weeks)?',
          detail: ['Reorders: every 6 weeks', 'Average order: £1,800'],
          shuffleOptions: false,
          options: [
            { id: 'a', text: '£10,800' },
            { id: 'b', text: '£15,600' },
            { id: 'c', text: '£18,000' },
            { id: 'd', text: '£21,600' },
            { id: 'e', text: '£93,600' },
          ],
        },
        {
          questionVersionId: 'sm-10',
          kind: 'single_choice',
          stem: 'What price per pack gives a 30% gross margin on this new bespoke welcome pack?',
          detail: ['Cost to Walter Geering: £3.15 a pack', 'Gross margin wanted: 30% of the selling price'],
          shuffleOptions: false,
          options: [
            { id: 'a', text: '£3.45' },
            { id: 'b', text: '£4.10' },
            { id: 'c', text: '£4.50' },
            { id: 'd', text: '£5.25' },
            { id: 'e', text: '£10.50' },
          ],
        },
      ],
    },
    {
      id: 'priorities',
      title: 'Priorities and judgement',
      instructions: [
        'There is no time limit in this section.',
        'For ranking questions, put the items in order using the arrows (most important at the top).',
      ],
      shuffleQuestions: true,
      scored: true,
      questions: [
        {
          questionVersionId: 'demo-q09',
          kind: 'ranking',
          stem: 'It is Monday morning. Put these tasks in the order you would do them.',
          options: [
            { id: 'call', text: 'Send the damage details to Customer Service for an accommodation manager whose welcome packs arrived damaged' },
            { id: 'quote', text: 'Send a £4,200 quote a hotel group’s purchasing manager asked for yesterday' },
            { id: 'crm', text: 'Update CRM notes from last week’s site visits' },
            { id: 'drive', text: 'Tidy the shared drive' },
          ],
        },
        {
          questionVersionId: 'demo-q10',
          kind: 'single_choice',
          stem: 'It is 4pm. You have made all 20 planned follow-up calls to hotels, but you have 2 of this week’s target of 3 new orders. What do you do?',
          options: [
            { id: 'a', text: 'Log the calls and finish – the plan for today is done' },
            { id: 'b', text: 'Call two hotels that asked for samples earlier in the week, then plan tomorrow' },
            { id: 'c', text: 'Email your manager an update' },
            { id: 'd', text: 'Plan tomorrow’s calls and finish for the day' },
          ],
        },
        {
          questionVersionId: 'demo-q11',
          kind: 'single_choice',
          stem: 'The operations manager of a hotel group you supply mentions they are opening a new 80-room hotel next month. What would you do?',
          options: [
            { id: 'a', text: 'Note it on their account and offer to plan amenities and linen for the opening' },
            { id: 'b', text: 'Congratulate them' },
            { id: 'c', text: 'Tell your manager and let them decide' },
            { id: 'd', text: 'Wait until they place an order' },
          ],
        },
        {
          questionVersionId: 'demo-q12',
          kind: 'single_choice',
          stem: 'A delivery of guest toiletries is going to arrive a day late, just before the hotel’s busy weekend. The head housekeeper has not noticed yet. What do you do?',
          options: [
            { id: 'a', text: 'Phone the head housekeeper now with the new date and their options' },
            { id: 'b', text: 'Wait and see whether they notice' },
            { id: 'c', text: 'Email the warehouse to ask why' },
            { id: 'd', text: 'Ask your manager what to do' },
          ],
        },
        {
          questionVersionId: 'demo-q14',
          kind: 'single_choice',
          stem: 'A hotel asks whether you can add its logo to the labels on its next order of welcome packs. What do you do?',
          options: [
            { id: 'a', text: 'Confirm it can be done as a bespoke order, explain the 3–5 working day lead time and send a quote' },
            { id: 'b', text: 'Ask a Director whether bespoke labels are allowed' },
            { id: 'c', text: 'Add the logo to the order now and sort out the price later' },
            { id: 'd', text: 'Tell the hotel to stick with standard packs to keep things simple' },
          ],
        },
        {
          questionVersionId: 'demo-q15',
          kind: 'single_choice',
          stem: 'On a site visit, the head housekeeper mentions that their dispenser refills keep running out mid-week. What would you do?',
          options: [
            { id: 'a', text: 'Offer a regular delivery sized to their usage, and follow up with a quote' },
            { id: 'b', text: 'Make a note to mention it on your next visit' },
            { id: 'c', text: 'Suggest they order more each time' },
            { id: 'd', text: 'Pass it to your manager to deal with' },
          ],
        },
        {
          questionVersionId: 'demo-q16',
          kind: 'single_choice',
          stem: 'At 4.45pm an operations manager emails: an amenities order for a wedding party this weekend is missing a box. What do you do?',
          options: [
            { id: 'a', text: 'Pass the full details to Customer Service now, and tell the operations manager it is in hand and when they will hear back' },
            { id: 'b', text: 'Reply first thing tomorrow, when you can find out more' },
            { id: 'c', text: 'Reply asking them to contact Customer Service' },
            { id: 'd', text: 'Ask your manager what to do' },
          ],
        },
        {
          questionVersionId: 'demo-q17',
          kind: 'single_choice',
          stem: 'You have an hour left today. Your CRM notes from today’s visits are not done, and a hotel group has just asked for a proposal covering its six sites. What do you do?',
          options: [
            { id: 'a', text: 'Call the hotel group to agree what the proposal needs, then write up your CRM notes before you finish' },
            { id: 'b', text: 'Write up your CRM notes – the hotel group can wait until tomorrow' },
            { id: 'c', text: 'Email the hotel group a price list and finish for the day' },
            { id: 'd', text: 'Ask a colleague to call the hotel group for you' },
          ],
        },
      ],
    },
    {
      id: 'motivation',
      title: 'What motivates you',
      instructions: [
        'There are no right or wrong answers here, and this section is not scored.',
        'It helps Walter Geering understand how to support and recognise you.',
      ],
      scored: false,
      purpose: 'motivation',
      questions: [
        {
          questionVersionId: 'demo-q13',
          kind: 'ranking',
          stem: 'Put these in order, from what matters most to you at work to what matters least.',
          options: [
            { id: 'progression', text: 'Opportunities to progress' },
            { id: 'recognition', text: 'Being recognised for good work' },
            { id: 'autonomy', text: 'Freedom to decide how I work' },
            { id: 'financial_reward', text: 'Financial reward' },
            { id: 'security', text: 'Stability and security' },
            { id: 'mastery', text: 'Becoming expert at what I do' },
            { id: 'team', text: 'Being part of a strong team' },
            { id: 'customer_impact', text: 'Making a difference for customers and their guests' },
          ],
        },
      ],
    },
  ],
};
