/**
 * "Live the Walter Geering Way – Put the Playbook into Practice": the question
 * bank (display only, no answers). Source: Walter Geering's "How Well Do You
 * Know Walter Geering?" bank (70 questions); IDs keep its numbering. Not
 * included: Q25–30 (need current internal figures) and Q31 (same as Q12).
 * Answers live in ./wgWayScoring.ts, which never reaches an employee's browser.
 */
import type { AssessmentDefinition, QuestionDef } from '../../../src/runner/index.js';

export const WG_WAY_TOPICS = {
  history: 'Walter Geering history & DNA',
  way: 'The Walter Geering Way',
  products: 'Products',
  supply: 'Supply, bespoke & lead times',
  playbook: 'Playbook',
  newbiz: 'New business: Four Calls to a Meeting',
} as const;
export type WgWayTopic = keyof typeof WG_WAY_TOPICS;

/** Questions too alike to appear in the same sitting. */
export const WG_WAY_NOT_TOGETHER: [string, string][] = [
  ['wg-13', 'wg-33'], // what CalliQ / the FLIRT score rewards
  ['wg-10', 'wg-44'], // Playbook phrases
  ['wg-10', 'wg-45'],
  ['wg-61', 'wg-53'], // Call 1
  ['wg-61', 'wg-54'],
];

/** Questions per sitting from each topic: 25 in all. */
export const WG_WAY_DRAW: Record<WgWayTopic, number> = { history: 4, way: 3, products: 3, supply: 2, playbook: 7, newbiz: 6 };

const BANK: QuestionDef[] = [
    {
      questionVersionId: 'wg-01',
      kind: 'single_choice',
      topic: 'history',
      stem: "In what year was Walter Geering founded?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "1898" },
        { id: 'b', text: "1903" },
        { id: 'c', text: "1912" },
        { id: 'd', text: "1923" },
      ],
    },
    {
      questionVersionId: 'wg-02',
      kind: 'single_choice',
      topic: 'history',
      stem: "What helped Walter Geering originally start the business?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "A £20 loan for a printing press" },
        { id: 'b', text: "A £500 bank loan" },
        { id: 'c', text: "A government grant" },
        { id: 'd', text: "An investment from a hotel group" },
      ],
    },
    {
      questionVersionId: 'wg-03',
      kind: 'single_choice',
      topic: 'history',
      stem: "What did Walter Geering originally begin with?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Hotel toiletries" },
        { id: 'b', text: "Welcome packs" },
        { id: 'c', text: "Printing" },
        { id: 'd', text: "Cleaning products" },
      ],
    },
    {
      questionVersionId: 'wg-04',
      kind: 'single_choice',
      topic: 'history',
      stem: "Which product became part of Walter Geering's early development during the 1920s?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Toiletry dispensers" },
        { id: 'b', text: "Shoe-shine cloths" },
        { id: 'c', text: "Welcome boxes" },
        { id: 'd', text: "Dog packs" },
      ],
    },
    {
      questionVersionId: 'wg-05',
      kind: 'single_choice',
      topic: 'history',
      stem: "Where is Walter Geering headquartered?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "London" },
        { id: 'b', text: "Canterbury" },
        { id: 'c', text: "Ashford, Kent" },
        { id: 'd', text: "Maidstone" },
      ],
    },
    {
      questionVersionId: 'wg-06',
      kind: 'single_choice',
      topic: 'history',
      stem: "Which statement best describes Walter Geering's philosophy?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "We sell toiletries" },
        { id: 'b', text: "We sell hospitality consumables" },
        { id: 'c', text: "We improve the guest experience" },
        { id: 'd', text: "We aim to be the cheapest supplier" },
      ],
    },
    {
      questionVersionId: 'wg-07',
      kind: 'single_choice',
      topic: 'history',
      stem: "Walter Geering should primarily be positioned as:",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Budget hospitality" },
        { id: 'b', text: "Affordable luxury" },
        { id: 'c', text: "High-price luxury" },
        { id: 'd', text: "General wholesale" },
      ],
    },
    {
      questionVersionId: 'wg-08',
      kind: 'single_choice',
      topic: 'history',
      stem: "What should normally be discussed before price?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Delivery charges" },
        { id: 'b', text: "Case quantities" },
        { id: 'c', text: "Guest experience and value" },
        { id: 'd', text: "Discounts" },
      ],
    },
    {
      questionVersionId: 'wg-09',
      kind: 'single_choice',
      topic: 'way',
      stem: "Which tone best represents Walter Geering?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Formal, corporate and scripted" },
        { id: 'b', text: "Aggressive and sales-driven" },
        { id: 'c', text: "Warm, confident, curious and naturally charming" },
        { id: 'd', text: "Casual and unstructured" },
      ],
    },
    {
      questionVersionId: 'wg-10',
      kind: 'single_choice',
      topic: 'way',
      stem: "Which phrase should a Walter Geering salesperson avoid?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Out of curiosity…" },
        { id: 'b', text: "Help me understand…" },
        { id: 'c', text: "Just checking in…" },
        { id: 'd', text: "Walk me through…" },
      ],
    },
    {
      questionVersionId: 'wg-11',
      kind: 'single_choice',
      topic: 'way',
      stem: "Which phrase is more Walter Geering?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "I was wondering whether you might be interested." },
        { id: 'b', text: "Out of curiosity, how are you currently approaching this?" },
        { id: 'c', text: "Can I send you a brochure?" },
        { id: 'd', text: "Hopefully we can help." },
      ],
    },
    {
      questionVersionId: 'wg-12',
      kind: 'single_choice',
      topic: 'way',
      stem: "What is the golden rule behind the Walter Geering FLIRT principle?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Sell first, discover later" },
        { id: 'b', text: "Be interesting before being interested" },
        { id: 'c', text: "Be interested before being interesting" },
        { id: 'd', text: "Always keep conversations short" },
      ],
    },
    {
      questionVersionId: 'wg-13',
      kind: 'single_choice',
      topic: 'way',
      stem: "Which behaviour should CalliQ reward?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Reading from a script" },
        { id: 'b', text: "Talking more than the customer" },
        { id: 'c', text: "Genuine curiosity and active listening" },
        { id: 'd', text: "Rapid-fire questioning" },
      ],
    },
    {
      questionVersionId: 'wg-14',
      kind: 'single_choice',
      topic: 'way',
      stem: "Which behaviour should CalliQ mark down?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Natural reactions" },
        { id: 'b', text: "Follow-up questions" },
        { id: 'c', text: "Celebrating customer success" },
        { id: 'd', text: "Robotic delivery" },
      ],
    },
    {
      questionVersionId: 'wg-15',
      kind: 'single_choice',
      topic: 'products',
      stem: "Which Walter Geering solution can help reduce the use of single-use miniature toiletry bottles?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Dog Welcome Packs" },
        { id: 'b', text: "Floating dispenser systems" },
        { id: 'c', text: "Kids packs" },
        { id: 'd', text: "Shoe cloths" },
      ],
    },
    {
      questionVersionId: 'wg-16',
      kind: 'single_choice',
      topic: 'products',
      stem: "Walter Geering Toiletry Sheets are available for which product types?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Shampoo only" },
        { id: 'b', text: "Shampoo and conditioner only" },
        { id: 'c', text: "Shampoo, conditioner and body wash" },
        { id: 'd', text: "Hand wash only" },
      ],
    },
    {
      questionVersionId: 'wg-17',
      kind: 'single_choice',
      topic: 'products',
      stem: "What is a major benefit of Walter Geering Toiletry Sheets?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "They require plastic bottles" },
        { id: 'b', text: "They reduce single-use plastic waste" },
        { id: 'c', text: "They need refrigeration" },
        { id: 'd', text: "They are designed only for residential use" },
      ],
    },
    {
      questionVersionId: 'wg-18',
      kind: 'single_choice',
      topic: 'products',
      stem: "Which are examples of Walter Geering Welcome Pack categories?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Holiday/changeover packs" },
        { id: 'b', text: "Kids packs" },
        { id: 'c', text: "Dog Welcome Packs" },
        { id: 'd', text: "All of the above" },
      ],
    },
    {
      questionVersionId: 'wg-19',
      kind: 'single_choice',
      topic: 'products',
      stem: "Which names are associated with Walter Geering Dog Welcome Packs?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Maggie, Perdy and Pongo" },
        { id: 'b', text: "Max, Alfie and Bertie" },
        { id: 'c', text: "Bella, Molly and Charlie" },
        { id: 'd', text: "Oscar, Monty and Milo" },
      ],
    },
    {
      questionVersionId: 'wg-20',
      kind: 'single_choice',
      topic: 'products',
      stem: "When talking about Walter Geering products, what should the salesperson primarily sell?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "The specification" },
        { id: 'b', text: "The case quantity" },
        { id: 'c', text: "The guest experience and outcome the product creates" },
        { id: 'd', text: "The cheapest option" },
      ],
    },
    {
      questionVersionId: 'wg-21',
      kind: 'single_choice',
      topic: 'supply',
      stem: "What is the approximate lead time for products sourced from China?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "4–6 weeks" },
        { id: 'b', text: "6–8 weeks" },
        { id: 'c', text: "12–16 weeks" },
        { id: 'd', text: "20–24 weeks" },
      ],
    },
    {
      questionVersionId: 'wg-22',
      kind: 'single_choice',
      topic: 'supply',
      stem: "What is the approximate lead time for products sourced from Turkey?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "2–4 weeks" },
        { id: 'b', text: "4–6 weeks" },
        { id: 'c', text: "8–10 weeks" },
        { id: 'd', text: "14–18 weeks" },
      ],
    },
    {
      questionVersionId: 'wg-23',
      kind: 'single_choice',
      topic: 'supply',
      stem: "A customer requires a bespoke product in six weeks. Which is the best Walter Geering response?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Promise that China can deliver it" },
        { id: 'b', text: "Take the order and worry about lead time later" },
        { id: 'c', text: "Explore UK stock, Turkey or another realistic alternative" },
        { id: 'd', text: "Tell the customer bespoke products are impossible" },
      ],
    },
    {
      questionVersionId: 'wg-24',
      kind: 'single_choice',
      topic: 'supply',
      stem: "How should a salesperson handle a longer bespoke lead time?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Avoid mentioning it until the order has been placed" },
        { id: 'b', text: "Be clear, manage expectations and explore the best solution" },
        { id: 'c', text: "Promise the requested delivery date regardless" },
        { id: 'd', text: "Reduce the price" },
      ],
    },
    {
      questionVersionId: 'wg-32',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "What is the purpose of the Walter Geering FLIRT Principle?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "To make conversations more informal" },
        { id: 'b', text: "To create human connection through curiosity, warmth, enthusiasm and professionalism" },
        { id: 'c', text: "To make salespeople more humorous" },
        { id: 'd', text: "To shorten the sales process" },
      ],
    },
    {
      questionVersionId: 'wg-33',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "Which behaviour should the AI FLIRT Score reward?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Product monologues" },
        { id: 'b', text: "Reading from a script" },
        { id: 'c', text: "Active listening and natural follow-up questions" },
        { id: 'd', text: "Moving quickly into qualification" },
      ],
    },
    {
      questionVersionId: 'wg-34',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "What should a salesperson do when a customer shares something exciting about their business?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Move quickly back to the product" },
        { id: 'b', text: "Ask who their supplier is" },
        { id: 'c', text: "Pause, acknowledge it and explore it with genuine curiosity" },
        { id: 'd', text: "Ask their budget" },
      ],
    },
    {
      questionVersionId: 'wg-35',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "According to the Walter Geering Charm Test, Walter Geering should sound like:",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "A traditional salesperson" },
        { id: 'b', text: "A luxury hospitality brand" },
        { id: 'c', text: "A catalogue wholesaler" },
        { id: 'd', text: "A procurement company" },
      ],
    },
    {
      questionVersionId: 'wg-36',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "Which description best passes the Walter Geering Charm Test?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Direct, aggressive and persistent" },
        { id: 'b', text: "Warm, relaxed, confident and curious" },
        { id: 'c', text: "Formal, detailed and corporate" },
        { id: 'd', text: "Fast-talking and enthusiastic" },
      ],
    },
    {
      questionVersionId: 'wg-37',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "What does the Walter Geering One-Chance Mentality mean?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Only call a prospect once" },
        { id: 'b', text: "Assume this may be the only conversation the prospect ever has with Walter Geering" },
        { id: 'c', text: "Try to close every opportunity on the first call" },
        { id: 'd', text: "Never follow up after an unsuccessful call" },
      ],
    },
    {
      questionVersionId: 'wg-38',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "Under the One-Chance Mentality, which statement is true?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Directness is a strength; pushiness is not" },
        { id: 'b', text: "Pushiness creates urgency" },
        { id: 'c', text: "Product knowledge matters more than curiosity" },
        { id: 'd', text: "The objective is always to close immediately" },
      ],
    },
    {
      questionVersionId: 'wg-39',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "Which is the best Walter Geering conversation style?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Ask several questions at once" },
        { id: 'b', text: "Give a detailed product presentation" },
        { id: 'c', text: "Ask one question at a time and listen more than you speak" },
        { id: 'd', text: "Follow the script exactly" },
      ],
    },
    {
      questionVersionId: 'wg-40',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "Which should a Walter Geering salesperson avoid?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Short, confident sentences" },
        { id: 'b', text: "Allowing silence" },
        { id: 'c', text: "Product monologues" },
        { id: 'd', text: "Building curiosity" },
      ],
    },
    {
      questionVersionId: 'wg-41',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "When dealing with a competitor, Walter Geering's approach should be to:",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Explain why the competitor is worse" },
        { id: 'b', text: "Discount immediately" },
        { id: 'c', text: "Acknowledge them, respect them and become curious" },
        { id: 'd', text: "Avoid mentioning them" },
      ],
    },
    {
      questionVersionId: 'wg-42',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "What should you never do when discussing a customer's existing supplier?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Ask what could be improved" },
        { id: 'b', text: "Respect the relationship" },
        { id: 'c', text: "Criticise the competitor" },
        { id: 'd', text: "Become curious" },
      ],
    },
    {
      questionVersionId: 'wg-43',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "What is the correct Walter Geering objection-handling sequence?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Discount → Defend → Close" },
        { id: 'b', text: "Understand → Clarify → Reframe" },
        { id: 'c', text: "Listen → Discount → Ask" },
        { id: 'd', text: "Explain → Defend → Quote" },
      ],
    },
    {
      questionVersionId: 'wg-44',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "Which phrase is encouraged in the WG Playbook?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Hopefully…" },
        { id: 'b', text: "Just checking in…" },
        { id: 'c', text: "Help me understand…" },
        { id: 'd', text: "If you're interested…" },
      ],
    },
    {
      questionVersionId: 'wg-45',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "Which phrase weakens confidence and should be avoided?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Walk me through…" },
        { id: 'b', text: "What would need to happen…" },
        { id: 'c', text: "Hopefully…" },
        { id: 'd', text: "Out of curiosity…" },
      ],
    },
    {
      questionVersionId: 'wg-46',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "What should the strongest Walter Geering salesperson do more of?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Speak" },
        { id: 'b', text: "Explain" },
        { id: 'c', text: "Listen" },
        { id: 'd', text: "Present" },
      ],
    },
    {
      questionVersionId: 'wg-47',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "What should a customer ideally think after a Walter Geering conversation?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "They know a lot about toiletries." },
        { id: 'b', text: "They were very persistent." },
        { id: 'c', text: "That was a genuinely good conversation. I actually liked them." },
        { id: 'd', text: "They were cheaper than expected." },
      ],
    },
    {
      questionVersionId: 'wg-48',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "What is Walter Geering ultimately trying to become in the customer's mind?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "The cheapest supplier" },
        { id: 'b', text: "The first supplier they think of when they want to improve their guest experience" },
        { id: 'c', text: "Their largest supplier" },
        { id: 'd', text: "Their toiletries wholesaler" },
      ],
    },
    {
      questionVersionId: 'wg-49',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "Which best describes the Walter Geering salesperson standard?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Calm, curious, confident, commercially aware, direct, likeable and memorable" },
        { id: 'b', text: "Fast, competitive, persuasive and persistent" },
        { id: 'c', text: "Formal, structured and product-focused" },
        { id: 'd', text: "Friendly, informal and price-led" },
      ],
    },
    {
      questionVersionId: 'wg-50',
      kind: 'single_choice',
      topic: 'playbook',
      stem: "Which statement best describes Walter Geering?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "We sell toiletries, welcome packs and hospitality supplies." },
        { id: 'b', text: "Our main aim is to be cheaper than other suppliers." },
        { id: 'c', text: "We help hospitality businesses create memorable guest experiences through thoughtful products, dependable service and trusted partnership." },
        { id: 'd', text: "We are a wholesaler with a large hospitality range." },
      ],
    },
    {
      questionVersionId: 'wg-51',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "What is the main principle behind the Walter Geering “Four Calls to a Meeting” process?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Every call should try to close the sale" },
        { id: 'b', text: "One call is enough if the pitch is strong" },
        { id: 'c', text: "Each call has one specific job and can build towards a meeting" },
        { id: 'd', text: "Email should always come before the first call" },
      ],
    },
    {
      questionVersionId: 'wg-52',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "What is the job of Call 1 in the new business process?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Sell the product" },
        { id: 'b', text: "Fact finding" },
        { id: 'c', text: "Ask for the order" },
        { id: 'd', text: "Send a proposal" },
      ],
    },
    {
      questionVersionId: 'wg-53',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "On Call 1, what should the salesperson try to establish?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Whether the hotel uses miniatures or dispensers and who looks after guest amenities" },
        { id: 'b', text: "Whether they want a price list" },
        { id: 'c', text: "Whether they will place an order today" },
        { id: 'd', text: "Whether they want samples immediately" },
      ],
    },
    {
      questionVersionId: 'wg-54',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "Why should the salesperson not pitch to whoever answers the phone?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "They may not be friendly" },
        { id: 'b', text: "They may not be the buyer or decision maker" },
        { id: 'c', text: "They may already know the products" },
        { id: 'd', text: "It makes the call too long" },
      ],
    },
    {
      questionVersionId: 'wg-55',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "What is the purpose of Call 2?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Send a brochure" },
        { id: 'b', text: "Ask for the decision maker" },
        { id: 'c', text: "Discuss price" },
        { id: 'd', text: "Offer samples" },
      ],
    },
    {
      questionVersionId: 'wg-56',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "If the decision maker's name is given during Call 2, what should happen next?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Go back to Call 1" },
        { id: 'b', text: "Send an introduction email" },
        { id: 'c', text: "Move straight to Call 4" },
        { id: 'd', text: "Wait two weeks" },
      ],
    },
    {
      questionVersionId: 'wg-57',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "What is the purpose of Call 3?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Present Walter Geering's full range" },
        { id: 'b', text: "Gain access to the decision maker when their name is guarded" },
        { id: 'c', text: "Discuss pricing" },
        { id: 'd', text: "Send samples" },
      ],
    },
    {
      questionVersionId: 'wg-58',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "What is the purpose of Call 4?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Sell the product" },
        { id: 'b', text: "Sell the meeting" },
        { id: 'c', text: "Quote the customer" },
        { id: 'd', text: "Close the order" },
      ],
    },
    {
      questionVersionId: 'wg-59',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "On Call 4, what should the salesperson primarily sell?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Toiletries" },
        { id: 'b', text: "The brochure" },
        { id: 'c', text: "The value of a short meeting" },
        { id: 'd', text: "A trial order" },
      ],
    },
    {
      questionVersionId: 'wg-60',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "What happens after the meeting is booked?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Send samples only" },
        { id: 'b', text: "Present a solution and Walter Geering as a partner" },
        { id: 'c', text: "Wait for the customer to contact us" },
        { id: 'd', text: "Send a generic price list" },
      ],
    },
    {
      questionVersionId: 'wg-61',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "What are the two jobs of the first call to a hotel group prospect?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Quote and close" },
        { id: 'b', text: "Find out whether they use miniatures or dispensers, and identify the decision maker" },
        { id: 'c', text: "Send samples and arrange delivery" },
        { id: 'd', text: "Discuss pricing and lead times" },
      ],
    },
    {
      questionVersionId: 'wg-62',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "What should happen before presenting Walter Geering as a solution?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Send an introduction email" },
        { id: 'b', text: "Qualify the prospect" },
        { id: 'c', text: "Send samples" },
        { id: 'd', text: "Discuss discounts" },
      ],
    },
    {
      questionVersionId: 'wg-63',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "Should a new hotel group prospect receive an introduction email before the first call?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Yes, always" },
        { id: 'b', text: "Yes, if they have more than one site" },
        { id: 'c', text: "No, the call should come first" },
        { id: 'd', text: "Only if they use miniatures" },
      ],
    },
    {
      questionVersionId: 'wg-64',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "Why does Walter Geering prefer a call before an introduction email?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Emails are too expensive" },
        { id: 'b', text: "The offering is too broad and can become reduced to a skimmed product list" },
        { id: 'c', text: "Customers never read emails" },
        { id: 'd', text: "Email is only used after an order" },
      ],
    },
    {
      questionVersionId: 'wg-65',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "When should email mainly be used in this new business process?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Before the first call" },
        { id: 'b', text: "Instead of calling" },
        { id: 'c', text: "After the call, to confirm a meeting or follow up" },
        { id: 'd', text: "Only after an order is placed" },
      ],
    },
    {
      questionVersionId: 'wg-66',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "What is the key qualifying question for hotel group prospects?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "How much do you spend each month?" },
        { id: 'b', text: "Do your hotels use miniatures or dispensers in the guest bathrooms?" },
        { id: 'c', text: "Who is your current supplier?" },
        { id: 'd', text: "Would you like free samples?" },
      ],
    },
    {
      questionVersionId: 'wg-67',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "According to the guidance, which type of prospect may be the easier market to win?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Hotels already using another supplier's dispenser system" },
        { id: 'b', text: "Hotels using miniatures" },
        { id: 'c', text: "Hotels with no bathrooms" },
        { id: 'd', text: "Hotels with no supplier" },
      ],
    },
    {
      questionVersionId: 'wg-68',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "Why may hotels already using dispensers be harder to win immediately?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "They do not buy toiletries" },
        { id: 'b', text: "They may already have another supplier's installed dispenser system" },
        { id: 'c', text: "They are always tied into long contracts" },
        { id: 'd', text: "They never change suppliers" },
      ],
    },
    {
      questionVersionId: 'wg-69',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "What may be the better approach with a prospect already using another supplier's dispenser system?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Push aggressively for an immediate change" },
        { id: 'b', text: "Qualify them for a later opportunity rather than forcing the issue now" },
        { id: 'c', text: "Offer an immediate discount" },
        { id: 'd', text: "Send samples without discussion" },
      ],
    },
    {
      questionVersionId: 'wg-70',
      kind: 'single_choice',
      topic: 'newbiz',
      stem: "Which statement best reflects the philosophy of the new business process?",
      shuffleOptions: false,
      options: [
        { id: 'a', text: "Every call must result in a sale" },
        { id: 'b', text: "Whoever answers should receive the full pitch" },
        { id: 'c', text: "Each call should have a clear purpose and move the prospect towards the right person and a meeting" },
        { id: 'd', text: "Emails are more important than calls" },
      ],
    },
];

export const WG_WAY_TEST: AssessmentDefinition = {
  version: 'wg-way-2026.1',
  title: 'Live the Walter Geering Way – Put the Playbook into Practice',
  estimatedMinutes: 10,
  sections: [
    {
      id: 'wg-way',
      title: 'Live the Walter Geering Way',
      instructions: [
        '25 quick questions about Walter Geering: our history, products, lead times, the Playbook and how we win new business.',
        'You have 10 minutes. Go with your first answer and keep moving – you can go back before you submit.',
        'Each sitting draws different questions, so there is nothing to memorise from a colleague.',
      ],
      timeLimitSeconds: 600,
      draw: WG_WAY_DRAW,
      notTogether: WG_WAY_NOT_TOGETHER,
      shuffleQuestions: true,
      scored: true,
      questions: BANK,
    },
  ],
};
