/**
 * Builds the SQL that loads FocusiQ's assessment content and privacy notice
 * into the `focusiq` schema. Review the output, then run it in the Supabase
 * SQL editor (or ask Claude to apply it).
 *
 *   npx vite-node scripts/content-sql.ts -- --out supabase/content/focusiq-2026.1.sql
 *
 * Options:
 *   --version <id>   assessment_versions.id (default focusiq-2026.1)
 *   --title <text>   title shown to employees (default "FocusiQ assessment")
 *   --test-fill      fill the notice's [[placeholders]] with obvious TEST text.
 *                    Only for a test database: never publish this to real staff.
 *
 * Without --test-fill the script refuses while the privacy notice still has
 * [[placeholders]] (the database would refuse to publish it anyway).
 *
 * Question ids become stable UUIDs (deterministicUuid), so re-running the
 * script produces the same rows; every insert is "on conflict do nothing", and
 * published rows can never be changed afterwards. To change content, publish a
 * new assessment version.
 */
import { writeFileSync } from 'node:fs';
import { NOTICE_V1, noticeFingerprint, placeholdersIn, type PrivacyNotice } from '../src/participation/index.js';
import { deterministicUuid } from '../src/runner/index.js';
import { DEMO_ASSESSMENT } from '../app/src/demo/assessment.js';
import { DEMO_SCORING } from '../app/src/demo/scoring.js';

const args = process.argv.slice(2);
const arg = (name: string) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
};
const version = arg('--version') ?? 'focusiq-2026.1';
const title = arg('--title') ?? 'FocusiQ assessment';
const out = arg('--out');
const testFill = args.includes('--test-fill');

const lit = (v: unknown) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const json = (v: unknown) => `${lit(JSON.stringify(v))}::jsonb`;

function noticeToPublish(): PrivacyNotice {
  if (!testFill) {
    const missing = placeholdersIn(NOTICE_V1);
    if (missing.length) {
      throw new Error(`The privacy notice still has ${missing.length} [[placeholders]] to complete in src/participation/notice.ts:\n- ${missing.join('\n- ')}`);
    }
    return NOTICE_V1;
  }
  const fill = (t: string) => t.replace(/\[\[([^\]]+)\]\]/g, (_m, label: string) => `TEST VALUE (${label})`);
  return {
    ...NOTICE_V1,
    version: `${NOTICE_V1.version}-test`,
    summary: NOTICE_V1.summary.map(fill),
    sections: NOTICE_V1.sections.map((s) => ({ ...s, heading: fill(s.heading), paragraphs: s.paragraphs.map(fill) })),
    acknowledgements: NOTICE_V1.acknowledgements.map((a) => ({ ...a, text: fill(a.text) })),
  };
}

async function main() {
  const notice = noticeToPublish();
  const sha = await noticeFingerprint({ ...notice, publishedAt: null });
  const lines: string[] = [
    `-- FocusiQ content: assessment ${version} and privacy notice ${notice.version}.`,
    `-- Generated by scripts/content-sql.ts${testFill ? ' with --test-fill (TEST DATABASE ONLY)' : ''}.`,
    'begin;',
  ];

  const families = new Map<string, string>();
  const questions: { id: string; uuid: string; family: string; content: unknown; key: unknown; meta: unknown }[] = [];
  for (const section of DEMO_ASSESSMENT.sections) {
    for (const q of section.questions) {
      const scoring = DEMO_SCORING[q.questionVersionId];
      const family = scoring?.family ?? (section.purpose === 'motivation' ? 'motivation' : section.id);
      families.set(family, scoring?.dimension ?? (section.purpose === 'motivation' ? 'motivation' : 'unscored'));
      const { questionVersionId, ...content } = q;
      const { correctAnswer, ...meta } = scoring ?? ({} as Record<string, unknown>);
      questions.push({
        id: questionVersionId,
        uuid: deterministicUuid(`${version}:${questionVersionId}`),
        family,
        content,
        key: correctAnswer === undefined ? null : { correctAnswer },
        meta: { ...meta, sectionId: section.id, scored: section.scored },
      });
    }
  }
  const uuidOf = new Map(questions.map((q) => [q.id, q.uuid]));

  for (const [id, dimension] of families) {
    lines.push(`insert into focusiq.question_families (id, dimension) values (${lit(id)}, ${lit(dimension)}) on conflict (id) do nothing;`);
  }
  for (const q of questions) {
    lines.push(`insert into focusiq.questions (id, family_id) values (${lit(q.id)}, ${lit(q.family)}) on conflict (id) do nothing;`);
    lines.push(
      `insert into focusiq.question_versions (id, question_id, version, content, answer_key, scoring_meta, published_at) values (${lit(q.uuid)}, ${lit(q.id)}, 1, ${json(q.content)}, ${q.key ? json(q.key) : 'null'}, ${json(q.meta)}, now()) on conflict (id) do nothing;`,
    );
  }

  // The runner's definition, with questions referred to by question_versions.id.
  const definition = {
    estimatedMinutes: DEMO_ASSESSMENT.estimatedMinutes,
    sections: DEMO_ASSESSMENT.sections.map(({ questions: qs, ...s }) => ({ ...s, questionVersionIds: qs.map((q) => uuidOf.get(q.questionVersionId)!) })),
  };
  lines.push(
    `insert into focusiq.assessment_versions (id, title, definition, published_at) values (${lit(version)}, ${lit(title)}, ${json(definition)}, now()) on conflict (id) do nothing;`,
  );
  let position = 0;
  for (const q of questions) {
    lines.push(
      `insert into focusiq.assessment_version_questions (assessment_version_id, question_version_id, position) values (${lit(version)}, ${lit(q.uuid)}, ${++position}) on conflict do nothing;`,
    );
  }

  const { version: nv, title: nt, publishedAt: _p, ...content } = notice;
  lines.push(
    `insert into focusiq.privacy_notices (version, title, content, content_sha256, published_at) values (${lit(nv)}, ${lit(nt)}, ${json(content)}, ${lit(sha)}, now()) on conflict (version) do nothing;`,
  );
  lines.push('commit;', '');

  const sql = lines.join('\n');
  if (out) {
    writeFileSync(out, sql);
    console.log(`Wrote ${out}: ${questions.length} questions, assessment ${version}, notice ${nv}.`);
  } else {
    process.stdout.write(sql);
  }
}

main().catch((e: Error) => {
  console.error(e.message);
  process.exit(1);
});
